app = "tradepulse-backend"

[build]
  image = "python:3.11"

[env]
  PORT = "8000"
  DATABASE_URL = "postgres://user:pass@host:port/dbname"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
